### ISSUE TITLE
Self-document the prediction API endpoint

### ISSUE THREAD

**Issue by pjbull** [concept-to-clinic/concept-to-clinic#10]
## Overview
A useful API will tell you how to use it. Update the API endpoints to be more helpful!

## Expected Behavior
Currently, there is just a placeholder if you `GET` our prediction API endpoints. We expect this call to tell us what the endpoint does, what the required parameters are, and what it returns.

To do this, we'll need to update our response payload to have that information.

## Technical details
 - This feature should be implemented in the [`prediction/src/views.py`](https://github.com/concept-to-clinic/concept-to-clinic/blob/master/prediction/src/views.py#L70-L74)
 - For each algorithm, we should add the right: `description`, `expected_parameters`, `return_values`
 - This feature should have tests for each algorithm in [`prediction/src/tests/test_endpoints.py`](https://github.com/concept-to-clinic/concept-to-clinic/blob/master/prediction/src/views.py#L70-L74)

## Acceptance criteria
 - [ ] accurately documents all three prediction endpoints
 - [ ] has passing tests

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by lamby** [comment]
Closed in https://github.com/concept-to-clinic/concept-to-clinic/pull/66. Thanks !
