### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by WGierke** [concept-to-clinic/concept-to-clinic#105]
Currently, two tests on the master branch are failing which seemingly has been introduced by PR #97 . It would be nice if the tests would pass again.

## Expected Behavior
All tests pass.

## Current Behavior
2 tests don't pass:
```
ERROR: test_landing (backend.static.tests.SmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/backend/static/tests.py", line 7, in test_landing
    url = reverse('static:open-image')
  File "/usr/local/lib/python2.7/dist-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'open-image' not found. 'open-image' is not a valid view function or pattern name.
======================================================================
ERROR: test_get_create_image_series (backend.images.tests.SmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/backend/images/tests.py", line 17, in test_get_create_image_series
    image_series, created = ImageSeries.get_or_create(uri)
TypeError: unbound method get_or_create() must be called with ImageSeries instance as first argument (got str instance instead)
```

## Steps to Reproduce
Check the [Travis build of the merge commit](https://travis-ci.org/concept-to-clinic/concept-to-clinic/builds/273792503) or
1. `git reset origin/master`
2. `bash tests/test_docker.sh `

## Possible Implementation
For the first test, it might make sense to replace the 'open-image' view name with 'home', since the 'open-image' view name has been replaced with 'home' [on the current master](https://github.com/concept-to-clinic/concept-to-clinic/blob/master/interface/backend/static/urls.py#L5). 

## Checklist before submitting
- [X] I have confirmed this using the officially supported Docker Compose setup using the `local.py` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [X] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [X] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [X] I provided **screenshots** where appropriate
- [X] I filled out all the relevant sections of this template

**Comment by isms** [comment]
These failing tests are both out of date as of 5ac1dee40bd89f08b612fb9678b02c01d9ad121c.

@WGierke Thanks for opening this! It's helpful to have open issues for bugs, however having multiple unrelated bugs in the same issue makes this extremely hard for contributors to track. Just a meta-note to help us all stay sane - in the future, (1) significant bugs should get their own issues, but (2) a failing build is sort of it's own bug report, so please be judicious in opening issues for small things that Travis is already announcing are broken.
