### ISSUE TITLE
Broken test: dicom.errors.InvalidDicomError in interface

### ISSUE THREAD

**Issue by isms** [concept-to-clinic/concept-to-clinic#109]
The `backend.images.tests.SmokeTest` test is broken.

## Expected Behavior
The test should pass.

## Current Behavior
Stack trace:
```
======================================================================
ERROR: test_get_create_image_series (backend.images.tests.SmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/backend/images/tests.py", line 17, in test_get_create_image_series
    image_series, created = ImageSeries.get_or_create(uri)
  File "/app/backend/images/models.py", line 30, in get_or_create
    plan = dicom.read_file(safe_join(uri, file_))
  File "/usr/local/lib/python3.6/site-packages/dicom/filereader.py", line 614, in read_file
    force=force)
  File "/usr/local/lib/python3.6/site-packages/dicom/filereader.py", line 515, in read_partial
    preamble = read_preamble(fileobj, force)
  File "/usr/local/lib/python3.6/site-packages/dicom/filereader.py", line 489, in read_preamble
    raise InvalidDicomError("File is missing 'DICM' marker. "
dicom.errors.InvalidDicomError: File is missing 'DICM' marker. Use force=True to force reading

----------------------------------------------------------------------
```

## Steps to Reproduce
1. Pull master branch and rebuild container.
2. Test `interface` with `sudo docker-compose -f local.yml run interface /test.sh`

**Comment by vsoch** [comment]
A lot of images have various bugs that will deem them unreadable (and I'm guessing by the error and suggestion you are using pydicom). Is there any reason you can't set force=True, as suggested by the output?

**Comment by isms** [comment]
@vsoch Yes and that's probably the right way to go. The current codepath is fragile because it assumes the existence of certain metadata fields.

**Comment by vsoch** [comment]
Which metadata fields are you concerned about? This error (afaik) mostly triggers due to the metadata of the file, not header fields (as maybe you are referring to?) One of those fields is called the preamble, which mostly serves to identify the file type (eg, DICM). For example, here is the metadata / preamble of a file:

```
from pydicom import read_file
dcm = read_file("AAA_1_11.dcm")   # note not using force
dcm.__dict__

{'_parent_encoding': 'iso8859',
 'file_meta': (0002, 0000) File Meta Information Group Length  UL: 94
(0002, 0001) File Meta Information Version       OB: b'\x00\x01'
(0002, 0002) Media Storage SOP Class UID         UI: ''
(0002, 0003) Media Storage SOP Instance UID      UI: ''
(0002, 0010) Transfer Syntax UID                 UI: Explicit VR Little Endian
(0002, 0012) Implementation Class UID            UI: ''
(0002, 0013) Implementation Version Name         SH: ''
(0002, 0016) Source Application Entity Title     SH: 'ARCHIVE',
 'filename': 'AAA_1_11.dcm',
 'fileobj_type': <function io.open>,
 'is_implicit_VR': False,
 'is_little_endian': True,
 'preamble': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
 'timestamp': 111111111111.0}
```

So if you are needing the preamble (or anything in the file above that isn't present), then you wouldn't want to set force=True. But I'm guessing for most machine learning you just need pixel data, and in this case most dicom (image data and header fields) are still readable with corrupt metadata, so setting force=True is a good idea.

I generally do force=True, and then have checks down the line for the specific things that I need.

**Comment by isms** [comment]
Lines like [this] (https://github.com/concept-to-clinic/concept-to-clinic/blob/master/interface/backend/images/models.py#L31) can, I think, fail.

I agree that the pixels matter most, so would like others working on this to double check that  trying to grab other fields can fail gracefully unless those fields are absolutely necessary to record somewhere (e.g. on our DB models for tracking the case).

**Comment by vsoch** [comment]
You could do a dicom.get("PatientId") which will default to None if not present (the Dataset class itself works like a dictionary) and then skip creation. It's very rare for PatientID to be missing, at least for the datasets I've used.

**Comment by isms** [comment]
@vsoch Thanks for the thoughtful comments - closing this as the original error has been superseded (by new better errors :chart_with_upwards_trend:) but appreciate your expertise on DICOM in the project!
