### ISSUE TITLE
Port existing pages to frontend Vue project

### ISSUE THREAD

**Issue by antonow** [concept-to-clinic/concept-to-clinic#110]
Before the base Vue app was merged ([PR 97](https://github.com/concept-to-clinic/concept-to-clinic/pull/97)), several frontend pages were developed and merged. These pages were being served from Django. It was later decided that all pages should be served from the single instance of the Vue app (see [here](https://github.com/concept-to-clinic/concept-to-clinic/issues/106#issuecomment-328642670)). As a result, these existing pages need to be ported over to the Vue app.

## Expected Behavior
The base Vue app in `interface/frontend/src/main.js` should serve all existing page templates using `VueRouter`. Clicking on a link should load the expected page template.

## Current Behavior
At the moment, only the navigation is displayed when loading the home route from Django and clicking on links in the navigation does not render any of the existing page templates.

## Possible Solution
The code from PR's [73](https://github.com/concept-to-clinic/concept-to-clinic/pull/73), [84](https://github.com/concept-to-clinic/concept-to-clinic/pull/84), [85](https://github.com/concept-to-clinic/concept-to-clinic/pull/85), [88](https://github.com/concept-to-clinic/concept-to-clinic/pull/88), [92](https://github.com/concept-to-clinic/concept-to-clinic/pull/92), and [93](https://github.com/concept-to-clinic/concept-to-clinic/pull/93) will need to be modified to use ES6 syntax and served from the Vue app using `VueRouter`.

## Steps to Reproduce
1. Fix the issue with the broken asset link as described in [issue 106](https://github.com/concept-to-clinic/concept-to-clinic/issues/106)
2. `cd interface/frontend && npm install && npm run build`
3. `cd ../..`
4. `docker-compose -f local.yml up`
5. Visit `localhost:8000` -- only the navigation appears

## Context (Environment)
Until the existing work is integrated into the base Vue app, it will be difficult to develop the remaining features which need to be built on top of these existing templates.

## Detailed Description
I am proposing to set up `VueRouter` and add all the necessary frontend routes to serve the page templates that have already been developed. These existing Vue components will also need to be updated to ES6 syntax in order for the frontend build process to succeed.

## Checklist before submitting
- [x] I have confirmed this using the officially supported Docker Compose setup using the `local.py` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [X] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [X] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [X] I provided **screenshots** where appropriate
- [X] I filled out all the relevant sections of this template

**Comment by isms** [comment]
Right on - marked as official. Thanks @antonow!

**Comment by isms** [comment]
Just FYI, @antonow @WGierke (cc @pjbull @lamby @reubano) as of the most recent changes this should be _much_ easier. Still lots to be worked out, but now we have a Vue.js+webpack config that runs a devserver at localhost:8080 which does hot reloading and proxies requests to `/api/[whatever]` to the `interface` container avoiding any need to share templates or mess with CORS.

Please check it out and file issues if there are any rough edges (protip: there will be lots of rough edges :sparkles:)

**Comment by louisgv** [comment]
I've read the issue and would like to participate in the refactor. 

Which piece of this issue has yet to be worked on?

**Comment by isms** [comment]
@louisgv Most of this frontend work still remains to be done! Recommend pulling the latest, building the Docker containers, and running the `docker-compose up -f local.yml vue` command to see what's there.

**Comment by isms** [comment]
Closing this omnibus issue in favor of more targeted issues.
