### ISSUE TITLE
small DICOM test images no longer managed in git

### ISSUE THREAD

**Issue by rahit** [concept-to-clinic/concept-to-clinic#116]
As of #95, DICOM images in `tests/assets/test_image_data/small` were moved from `git-lfs` directly to `git`. They now appear to be included in `git-lfs`.

## Expected Behavior

DICOM images in `tests/assets/test_image_data/small` should be directly managed `git`

## Current Behavior

DICOM images in `tests/assets/test_image_data/small` are linked via `git-lfs`

## Possible Solution

This appears to be a bug introduced by commit [#740af48](https://github.com/concept-to-clinic/concept-to-clinic/commit/740af48fc8fc248fa47242f3e0ea39db081cb71b) from #76.  I suspect the culprit is [somewhere here in `.gitattributes`](https://github.com/concept-to-clinic/concept-to-clinic/pull/76/files#diff-fc723d30b02a4cca7a534518111c1a66).

## Steps to Reproduce

```bash
git checkout 9b1c31
cd tests/assets/test_image_data/small/LIDC-IDRI-0001/
file  '1.3.6.1.4.1.14519.5.2.1.6279.6001.298806137288633453246975630178/1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192/-100.000000.dcm'
```

`output`
`1.3.6.1.4.1.14519.5.2.1.6279.../-100.000000.dcm: DICOM medical imaging data`

```bash
git checkout 740af4
file  '1.3.6.1.4.1.14519.5.2.1.6279.6001.298806137288633453246975630178/1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192/-100.000000.dcm'
```
`output`
`1.3.6.1.4.1.14519.5.2.1.6279.../-100.000000.dcm: ASCII text`

I encountered this while trying to load metadata information as of #33 

## Possible Implementation

@Serhiy-Shekhovtsov @vessemer any ideas?

## Checklist before submitting
- [x] I have confirmed this using the officially supported Docker Compose setup using the `local.py` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [x] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [x] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [x] I provided **screenshots** where appropriate
- [x] I filled out all the relevant sections of this template

**Comment by WGierke** [comment]
Hey @rahit could you give a complete piece of code that throws the error, please? That would make it a bit easier to reproduce the error I think :)

**Comment by rahit** [comment]
```
path = '/images/LIDC-IDRI-0002/' \
            '1.3.6.1.4.1.14519.5.2.1.6279.6001.490157381160200744295382098329/' \
            '1.3.6.1.4.1.14519.5.2.1.6279.6001.619372068417051974713149104919/-80.750000.dcm'
ds = dicom.read_file(path, force=True)    # At first tried without force=True
```

**Comment by rahit** [comment]
@WGierke  I think it is my fault. read_file is not raising the error. I am calling `repr(ds)` after which is producing the error. However, I can not load image using [ImageJ](https://apps.ubuntu.com/cat/applications/imagej/)

**Comment by rahit** [comment]
Here what I am trying to do.
```
dicom_dict = {}
repr(ds) # <-------------- KeyError: "Unknown DICOM tag (6576, 7372) - can't look up VR"
for dicom_value in ds:
    if dicom_value.tag == (0x7fe0, 0x0010):
        # discard pixel data
        continue
    else:
        dicom_dict[dicom_value.tag] = self._convert_value(dicom_value.value)
```

Simple loop:
```
for dicom_value in ds: # <-------------- KeyError: "Unknown DICOM tag (6576, 7372) - can't look up VR"
    pass
```

**Comment by reubano** [comment]
Thanks for the report. I'm looking into it.

**Comment by reubano** [comment]
I've confirmed...

```bash
git checkout 9b1c31
cd /tests/assets/test_image_data/small
ipython
```

```python
>>> import dicom
>>> path = 'LIDC-IDRI-0002/' \
...    '1.3.6.1.4.1.14519.5.2.1.6279.6001.490157381160200744295382098329/' \
...    '1.3.6.1.4.1.14519.5.2.1.6279.6001.619372068417051974713149104919/' \
...    '-80.750000.dcm'
>>> ds = dicom.read_file(path, force=True)    # At first tried without force=True
>>> repr(ds)
"(0008, 0005) Specific Character Set              CS: 'ISO..."
<CTRL-C>
```

```bash
git checkout 740af4
ipython
```

```python
>>> import dicom
>>> path = 'LIDC-IDRI-0002/' \
...    '1.3.6.1.4.1.14519.5.2.1.6279.6001.490157381160200744295382098329/' \
...    '1.3.6.1.4.1.14519.5.2.1.6279.6001.619372068417051974713149104919/' \
...    '-80.750000.dcm'
>>> ds = dicom.read_file(path, force=True)    # At first tried without force=True
>>> repr(ds)
KeyError: "Unknown DICOM tag (6576, 7372) - can't look up VR"
```

So it appears to be a bug introduced by commit [#740af48](https://github.com/concept-to-clinic/concept-to-clinic/commit/740af48fc8fc248fa47242f3e0ea39db081cb71b) from #76. I suspect the culprit is [somewhere here in `.gitattributes`](https://github.com/concept-to-clinic/concept-to-clinic/pull/76/files#diff-fc723d30b02a4cca7a534518111c1a66)
