### ISSUE TITLE
Use SimpleITK to load DICOM-images

### ISSUE THREAD

**Issue by tdraebing** [concept-to-clinic/concept-to-clinic#121]
## Expected Behavior

DICOM-images and -series should be loaded using the `SimpleITK`-package.

## Current Behavior

Currently DICOM-images are loaded into memory by using `pydicom` and `dicom-numpy` in `load_dicom.py`. A pull request (#119) is on its way to load mhd-images with SimpleITK. To reduce dependencies and make the code easier to maintain, SimpleITK should be used to load DICOM-images as well.

## Possible Solution

The [SimpleITK docs](http://simpleitk.readthedocs.io/en/master/Examples/DicomSeriesReader/Documentation.html) contain an example how to load a DICOM-image. The pydicom-objects are currently used at several places in the code. These usages will have to be refactored to deal with ITKImage objects. It would also be best to wait for #119 to be merged.

## Acceptance criteria

- [ ] DICOM-images are loaded into memory by SimpleITK.
- [ ] pydicom and dicom-numpy are removed from the dependencies.
- [ ] Code dependent on pydicom-objects is refactored to work with SimpleITK Image objects.

**Comment by reubano** [comment]
Is there anything that the `pydicom` / `dicom-numpy` duo can do that can't (easily) be done with `SimpleITK`? From briefly looking over the docs, `SimpleITK` appears to be a bit more verbose and less pythonthic. 

```
import SimpleITK as sitk

reader = sitk.ImageSeriesReader()
dicom_names = reader.GetGDCMSeriesFileNames('/path/to/dicom/files')
reader.SetFileNames(dicom_names)
image = reader.Execute()
reader.GetMetaData(0, '0010|0010')
```

vs

```
import dicom

image = dicom.read_file('/path/to/dicom/files')
ds.PatientsName
```

I also found `pydicom`'s docs a bit more comprehensive / easier to understand.

Thoughts?

**Comment by tdraebing** [comment]
SimpleITK as a port from C/C++ is for sure not really pythonic and accessing metadata is for sure a pain having to use the encoded tags. My idea was to keep the number of dependencies small and to be more consistent in what packages we use for the tasks. 
Also SimpleITK uses C in the backend as far as I understand and might therefor be faster. Although this might be more important if we would use it to also do preprocessing/transformation with SimpleITK. I could try some benchmarks on the weekend.

**Comment by reubano** [comment]
> SimpleITK as a port from C/C++ is for sure not really pythonic and accessing metadata is for sure a pain having to use the encoded tags. My idea was to keep the number of dependencies small and to be more consistent in what packages we use for the tasks.

In this case, I feel like the pro of removing a dependency don't outweigh the con of enforcing a less pythonic library. 

> Also SimpleITK uses C in the backend as far as I understand and might therefor be faster. Although this might be more important if we would use it to also do preprocessing/transformation with SimpleITK. I could try some benchmarks on the weekend.

Don't worry about that right now. For the MVP, we aren't really worrying about speed. Be on the lookout however, as we may want to start benchmarking and optimizing later on (at which point we can reopen this issue).
