### ISSUE TITLE
AttributeError: module 'src.algorithms.classify' has no attribute 'trained_model'

### ISSUE THREAD

**Issue by vlavorini** [concept-to-clinic/concept-to-clinic#123]
I'm using the official Docker development configuration. I only cloned repository, set up the docker environment (copy-paste from the instructions), and opened the page at localhost:8001

I expected to see the sort of welcome page, but I saw just the debugger page, with the error you read in the title.

A possible solution:
In the file:
concept-to-clinic/prediction/src/views.py
change two rows:

#from .algorithms import classify
to
from .algorithms.classify import trained_model

and 

#'classify': classify.trained_model.predict,
to
'classify': trained_model.predict,
    

## Steps to Reproduce
1. set up a clean environment
2. run docker-compose -f local.yml up
3. open http://localhost:8001

## Checklist before submitting
- [x] I have confirmed this using the officially supported Docker Compose setup using the `local.py` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [x ] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [x] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [] I provided **screenshots** where appropriate
- [x] I filled out all the relevant sections of this template

P.S.
'local.py' in the checklist should be 'local.yml', right?

**Comment by WGierke** [comment]
Thanks for filing the issue @vlavorini . I think I resolved it by adding the missing content to `__init__.py`, which has been added for the identify and segment algorithm folders but not for the classify one. Can you pull my branch `123_attribute_error` and verify whether it works for you there as well?

**Comment by VictorArias24** [comment]
very thanks @vlavorini This was my problem hours ago.

**Comment by reubano** [comment]
> 'local.py' in the checklist should be 'local.yml', right?

Is there a typo somewhere in the docs? If so, mind submitting another issue about it? Thanks!
