### ISSUE TITLE
Pass calculated summary statistics from segment model to API

### ISSUE THREAD

**Issue by pjbull** [concept-to-clinic/concept-to-clinic#14]
## Overview
Once we produce summary statistics for tumors, those need to be returned to the frontend through the API.

## Expected Behavior
Currently, the `segment` endpoint only returns a path to a file which has a binary mask of the DICOM image. This is useful for displaying the nodules, but we also want to report summary statistics. This issue tracks taking both the summary statistic calculations and the path to the binary masks generated by `segment.trained_model.predict` and surfacing both of those pieces of information through the API.

Design doc reference:
[Jobs to be done > Detect and select > Prediction service](https://concept-to-clinic.readthedocs.io/en/latest/design-doc.html#prediction-service)

## Technical details
 - This feature should be implemented in [views.py](https://github.com/concept-to-clinic/concept-to-clinic/blob/master/prediction/src/views.py) for the prediction application and wherever else down the stack is necessary to pass along the data 

## Related issues

Depends on #13, which tracks actually calculating the volumes. It's acceptable to create a stub for that work and implement this independently. You may need to read #13 to fully understand this issue.

## Acceptance criteria
 - [ ] An API endpoint for nodule summary statistics
 - [ ] documentation for the summary statistics endpoint

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by datu925** [comment]
Hi @pjbull! Acceptance criteria for this issue seems to be a carryover from the identification model.

**Comment by pjbull** [comment]
Hey @datu925!! Good to see you here! I've updated those, good catch. 🙇

**Comment by reiinakano** [comment]
Interested in this issue but am a bit unclear on exact details of the expected API.

Should I modify the return result of `POST segment/predict` to include summary statistics? Or should I create a new endpoint, say `GET/POST segment/statistics`, that take the binary mask path and outputs the volumes?
