### ISSUE TITLE
Slack workspace

### ISSUE THREAD

**Issue by Serhiy-Shekhovtsov** [concept-to-clinic/concept-to-clinic#144]
Guys, what do you think about creating a slack workspace for team communication? Many times when I got into a problem\question I don't know where to put it (forum is not active and github issues probably is not the best place for general questions). Also there is no simple\proper way to reach the person when question is not related to specific issue or pull request.

**Comment by reubano** [comment]
That's a great idea.. there's also gitter which i've noticed a lot of open source projects use. I'll bring this up to the rest of the team.

**Comment by vinitajha** [comment]
i have joined this competition, i am unable to download data, can you please advise

**Comment by reubano** [comment]
@vinitajha which data specifically is causing you trouble?

**Comment by reubano** [comment]
I see what you mean about the forums. I'll see if there is a way to ensure we get notified about new posts. If that were to happen, would it be sufficient?

**Comment by calvernaz** [comment]
Soo, any progress on the slack workspace front? :)

**Comment by isms** [comment]
Created a gitter for the project here: https://gitter.im/concept-to-clinic (thanks @reubano for suggesting!)

**Comment by AYSH20** [comment]
[Basecamp](https://basecamp.com/) is another great source for team communication. It has a learning curve but it helps in project management as well.

**Comment by isms** [comment]
Thanks for the suggestion @AYSH20! I think we're going to steer clear of adding a bunch more tools into the mix but it's worth thinking about.
