### ISSUE TITLE
Vue: implement 'Segmentation' UI component(s)

### ISSUE THREAD

**Issue by isms** [concept-to-clinic/concept-to-clinic#150]
### This issue will remain open until all the checkboxes are checked! PRs can reference this issue and will get credit even if the whole issue is not yet closed :+1:

Note: split off from #110 

---

Design doc reference here: http://concept-to-clinic.readthedocs.io/en/latest/design-doc.html#segment

Mock-up:
![](http://concept-to-clinic.readthedocs.io/en/latest/_images/wireframe-2-2-annotation-and-segmentation-segment.svg)

## Expected Behavior

- [ ] Display an image view of a given slice of the selected nodule. Allow navigation between slices.
- [ ] Overlay the current vertices on top of the nodule image to see the predicted boundary.
- [ ] Allow the user to move existing vertices.
- [ ] Allow the user to delete existing vertices.
- [ ] Allow the user to add a new vertex splitting a line segment connecting two vertices.
- [ ] Allow the user to extend the nodule boundary along the Z axis by extending the currently terminal polygon up or down to the adjacent slice which still has unhighlighted nodule.
- [ ] Indicate to the user the Z axis extent of slices.

## Mocking data

Feel free to mock data for `state` if it is not yet implemented in the backend API, and feel free to `POST` to API endpoints that don't exist yet :sparkles:

**Comment by swederik** [comment]
In Cornerstone Tools (https://github.com/chafey/cornerstoneTools) we have an ROI tool that could be a good starting point for building the nodule boundary selection tool: 
https://rawgit.com/chafey/cornerstoneTools/master/examples/freehandRoi/index.html

**Comment by jjjmm** [comment]
i am planning to start implementing this component on this weekend, if no one wants to start earlier

**Comment by jjjmm** [comment]
@isms I have a question about Segmentation component. Should it be in the sync with Annotate component? When nodule in Annotate selected, should it be also selected in Segmentation component? If so, could i put both Annotate and Segmentation components under the same Nodule (as on added picture)? If i understood correctly, both components represent data of same nodule ![segmentation](https://user-images.githubusercontent.com/17836809/31794931-96876f48-b52c-11e7-8a20-0180e86aacac.png)
 Or selection actions should be independent and implemented as on current design mock?

**Comment by isms** [comment]
@jjjmm Yes, they should be in sync, the segmentation screen on the right is showing the same nodule so that the radiologist can see what they are annotating and validate or redraw the predicted borders.

Thanks for asking!

**Comment by Serhiy-Shekhovtsov** [comment]
@jjjmm are you still working on this issue? If yes, do you need any help?

**Comment by jjjmm** [comment]
@Serhiy-Shekhovtsov currently not, you can take this issue if you want

**Comment by Serhiy-Shekhovtsov** [comment]
I am taking it. If anyone willing to join - please, put a comment or ping me on [gitter](https://gitter.im/concept-to-clinic/Lobby), so we can collaborate on this.

**Comment by vessemer** [comment]
I'm currently working on that, but only over `cornerstone-tools` segmentation part, thus will be glad to collaborate on this :)

**Comment by Serhiy-Shekhovtsov** [comment]
Have a look at [Area Canvas Editor](https://github.com/neshte/jquery-canvas-area-draw) as well:

![Area Canvas Editor](http://g.recordit.co/dTjU1H0KV0.gif)

It has some advantages over ROI tool:
1. no `cornerstone-tools` dependency, you can put it in any div element. and you can make a separate `Vue.js` component
2. user can add new points to existing area
3. user can remove points
4. dragging of entire area. It doesn't work on demo page, but I can see it in the code, so we can debug and fix it
5. the code looks pretty clear, we can probably improve it and get rid of jQuery dependency

I didn't start implementing such component yet, only did small research.

**Comment by Serhiy-Shekhovtsov** [comment]
@vessemer I have copied and improved the [mentioned project](https://github.com/neshte/jquery-canvas-area-draw) to fit our needs in this PR: #249.

![vue-area-select](http://g.recordit.co/HERuf4ckeD.gif)

**Comment by lamby** [comment]
Fixed in https://github.com/concept-to-clinic/concept-to-clinic/commit/5ffde736410e4fd47fad7d4b9f2456f1ff4a37d4

**Comment by Serhiy-Shekhovtsov** [comment]
@lamby I think it's too early to close this one yet :) I've only implemented a component for area selection, but still there things to be implemented:
-  Display an image view of a given slice of the selected nodule. Allow navigation between slices.
    - Code from #148 can be used as an example
-  Overlay the current vertices on top of the nodule image to see the predicted boundary.
    - The component is ready, we should read the area and initialize `AreaSelect`
- Allow the user to move existing vertices.
    ✔ already supported by `AreaSelect`, we should listen to `selection-changed` event and update the model
-  Allow the user to delete existing vertices.
-  Allow the user to add a new vertex splitting a line segment connecting two vertices.
    - Not sure what this is means :) 
-  Allow the user to extend the nodule boundary along the Z axis by extending the currently terminal polygon up or down to the adjacent slice which still has unhighlighted nodule.
    - We should observe `stack.currentImageIdIndex` change and reinit `AreaSelect` to display the nodule area at current slice
-  Indicate to the user the Z axis extent of slices.
    ✔ already supported by DICOM viewer

**Comment by isms** [comment]
@lamby I agree with @Serhiy-Shekhovtsov - this is not done. Reopening.

**Comment by pjbull** [comment]
As a heads up for anyone thinking about this issue, the DrivenData team be doing some work on this feature for some upcoming demos, so the master branch is subject to change!

**Comment by Serhiy-Shekhovtsov** [comment]
@louisgv are you working on this?

**Comment by louisgv** [comment]
No I am not

**Comment by Serhiy-Shekhovtsov** [comment]
Cool. I will take it and finish this page.

**Comment by wanghaisheng** [comment]
can i annotate some area with rectangle ?

**Comment by Serhiy-Shekhovtsov** [comment]
@wanghaisheng sorry, didn't get your question. With this tool you can select an area of any shape.
Btw, this issue can be closed now. as it has been implemented in #291
