### ISSUE TITLE
Python 3.6: RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII

### ISSUE THREAD

**Issue by WGierke** [concept-to-clinic/concept-to-clinic#152]
`docker-compose build` throws a RuntimeError in the prediction service:

```bash
prediction_1  | Traceback (most recent call last):
prediction_1  |   File "/usr/local/bin/flask", line 11, in <module>
prediction_1  |     sys.exit(main())
prediction_1  |   File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 513, in main
prediction_1  |     cli.main(args=args, prog_name=name)
prediction_1  |   File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 380, in main
prediction_1  |     return AppGroup.main(self, *args, **kwargs)
prediction_1  |   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 676, in main
prediction_1  |     _verify_python3_env()
prediction_1  |   File "/usr/local/lib/python3.6/dist-packages/click/_unicodefun.py", line 118, in _verify_python3_env
prediction_1  |     'for mitigation steps.' + extra)
prediction_1  | RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.
prediction_1  | 
prediction_1  | This system supports the C.UTF-8 locale which is recommended.
prediction_1  | You might be able to resolve your issue by exporting the
prediction_1  | following environment variables:
prediction_1  | 
prediction_1  |     export LC_ALL=C.UTF-8
prediction_1  |     export LANG=C.UTF-8
prediction_1 exited with code 1
```
## Possible Solution
Adding
```bash
LC_ALL=C.UTF-8  
LANG=C.UTF-8
```
as suggested to local.yml seems to fix the problem.

## Steps to Reproduce
`git fetch origin`  
`git checkout master`  
`git pull`  
`docker-compose -f local.yml build`  
`docker-compose -f local.yml up`  

Can someone reproduce this?

## Checklist before submitting
- [X] I have confirmed this using the officially supported Docker Compose setup using the `local.yml` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [X] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [X] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [X] I provided **screenshots** where appropriate
- [X] I filled out all the relevant sections of this template

**Comment by reubano** [comment]
Got the same error

**Comment by isms** [comment]
@reubano @WGierke can you set those two env vars in the Dockerfile and see if it solves the problem? If so they're harmless.

**Comment by reubano** [comment]
Yes... setting it in `local.yml` solved it.
