### ISSUE TITLE
Add to docs how to generate some JSON data to work with

### ISSUE THREAD

**Issue by isms** [concept-to-clinic/concept-to-clinic#153]
I [posted](https://github.com/concept-to-clinic/concept-to-clinic/issues/149#issuecomment-335625985) about how to get some JSON to work with, especially for people focusing on the frontend. This should live in the docs.

Easy points for any Markdown-lovers and/or docs fanatics out there :books:

**Comment by WGierke** [comment]
Is there anything left that prevents this issue from getting closed?
