### ISSUE TITLE
Give interface backend a home route

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#157]
## Overview
Currently, navigating to `http://0.0.0.0:8000/` returns a `404` error.

![screen shot 2017-10-16 at 1 33 29 am](https://user-images.githubusercontent.com/157864/31589968-14d235c2-b212-11e7-9553-8c79db8fa82e.png)

## Steps to Reproduce

1. `docker-compose -f local.yml up interface`
2. `open http://0.0.0.0:8000/`

## Expected Behavior

This url should route to a page listing all the available routes

## Technical details

- This feature should be implemented in the [`interface/backend/api/`](https://github.com/concept-to-clinic/concept-to-clinic/tree/master/interface/backend/api) folder.

## Acceptance criteria

 - [ ] Navigating to `http://0.0.0.0:8000/` should produce a helpful page with links to the available routes.

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by vessemer** [comment]
Is there something else left that prevents this issue from getting closed?

**Comment by reubano** [comment]
nope... thanks for the reminder
