### ISSUE TITLE
Remove hidden files from Vue frontend

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#158]
## Overview
Currently, when you navigate to `http://0.0.0.0:8080/` and click to expand the folders, you see hidden files such as `. DS_Store`.

![screen shot 2017-10-14 at 11 02 12 pm](https://user-images.githubusercontent.com/157864/31590120-c04effa6-b213-11e7-9ce7-50b7aa5a4d3c.png)

## Steps to Reproduce

1. `docker-compose -f local.yml up vue`
1. `open http://0.0.0.0:8080/`
1. Expand the pluses to navigate into the folders

## Expected Behavior

The hidden files should not be visible

## Technical details

- This feature should be implemented in the [`interface/frontend/src/`](https://github.com/concept-to-clinic/concept-to-clinic/tree/master/interface/frontend/src) folder.

## Acceptance criteria

 - [ ] Navigating to `http://0.0.0.0:8080/` and expanding the folders should not reveal any hidden files.

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by jjjmm** [comment]
wouldn't it be better to filter directories in the interface backend, before sending them to the frontend?

**Comment by reubano** [comment]
Good idea @jjjmm! I've added the backend label as well now.

**Comment by jjjmm** [comment]
@reubano btw, is there any instructions, how can i debug interface-backend in docker?

**Comment by reubano** [comment]
@jjjmm try `docker-compose -f local.yml up --build interface`

**Comment by lamby** [comment]
Merged :)
