### ISSUE TITLE
Make the docker-compose documentation service reuse the caches from prediction and interface

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#159]
## Overview
Currently, when running `docker-compose -f local.yml build`, the `documentation` service ignores the caches created by the `prediction` and `interface` services. This results in re-downloading all the python requirements.

## Expected Behavior
The `documentation` service should use the available caches and not re-download any python requirements.

## Technical details

- [Relevant `docker-compose` issue](https://github.com/docker/compose/issues/963) (also includes a few suggestions)

- [Another issue](https://github.com/docker/compose/issues/2828) which displays the desired behavior

- This feature should be implemented in the [`compose/documentation/Dockerfile-dev`](https://github.com/concept-to-clinic/concept-to-clinic/tree/master/compose/documentation/Dockerfile-dev), [`compose/prediction/Dockerfile-dev`](https://github.com/concept-to-clinic/concept-to-clinic/tree/master/compose/prediction/Dockerfile-dev), [`compose/interface/Dockerfile-dev`](https://github.com/concept-to-clinic/concept-to-clinic/tree/master/compose/interface/Dockerfile-dev), and [`local.yml`](https://github.com/concept-to-clinic/concept-to-clinic/tree/master/local.yml) files.

## Acceptance criteria

 - [ ] when running `docker-compose -f local.yml build` on a clean system, the python requirements files should not be downloaded by `documentation` service. 
 - [ ] when running `docker-compose -f local.yml build` on a clean system, the `documentation` service should use the caches provided by the `prediction` and `interface` services.

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by WGierke** [comment]
A friend of mine proposes that we should build our own base image which is based on the union of the pip requirements. Those, the base image is only supposed to be compiled once. If services use different versions of a library, they have to install them themselves after the base image was created. Just throwing in my two cents :)
