### ISSUE TITLE
Update travis tests to catch route errors

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#160]
## Overview
Currently, the travis test passes even if some routes are non-functional.

E.g.

- `git checkout 317b8c18`
- `docker-compose -f local.yml build`
- `sh tests/test_docker.sh`  # tests should pass
- `docker-compose -f local.yml up`
- `open http://0.0.0.0:8001/`  # page should error

## Expected Behavior
Travis should test all navigable routes and ensure that they properly function.

## Technical details

At a minimum, the following home pages should be tested:

- http://0.0.0.0:8000/
- http://0.0.0.0:8001/
- http://0.0.0.0:8080/

The appropriate routes for each home page should be tested as well.

e.g., `http://0.0.0.0:8000/api` and `http://0.0.0.0:8001/classify/predict`

- This feature should be implemented in the [`tests/test_docker.sh`](https://github.com/concept-to-clinic/concept-to-clinic/tree/master/tests/test_docker.sh) file.

## Acceptance criteria

 - [ ] The travis test should fail if any of the service routes produces an error. 

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by adrianjoseph** [comment]
Hi Reubano, 
What are you looking for when you say that the pages should be "tested"? In other words, what qualifies as "tested"? Also, what is a "travis test"

From what I can see:
http://0.0.0.0:8000/ - Has a 404 page not found error
http://0.0.0.0:8001/ - Gets a "ERR_CONNECTION_REFUSED" error
http://0.0.0.0:8080/ - This page loads and it seems you can see a drill down of a set of related fil

As an fyi: I am trying to get my feet wet with this process, so some of the asks may seem basic, but I am just trying to understand how to view and make changes where applicable.

**Comment by reubano** [comment]
Hi @adrianjoseph [these are the travis tests](https://travis-ci.org/concept-to-clinic/concept-to-clinic). It runs the tests [in this file](https://github.com/concept-to-clinic/concept-to-clinic/blob/master/tests/test_docker.sh). So by "the pages should be tested", I mean that if you checkout commit `317b8c18`, the travis tests should fail since not all the routes work. Does that make sense?

**Comment by isms** [comment]
I'm still not clear on why we would want a gigantic integration test instead of testing the services individually?

**Comment by reubano** [comment]
@isms mind giving an example of the sort of "individual service test" you mean? One way to speed things up could be reducing the [`TIMEOUT`](https://github.com/WGierke/concept-to-clinic/blob/0e359716e632b668aebcbfe8a86364610702453e/tests/test_routes.py#L6).

**Comment by isms** [comment]
@reubano It seems like this is essentially testing Docker by seeing if the services specified in `docker-compose.yml` show up, no? In each case you could write a simple unit (or functional) test for the service in question to make sure it's working (e.g. not 404, not ERR_CONNECTION_REFUSED).

This is not a good way to test whether each of the services are working as designed (except for painfully indirectly by spinning up _all_ the services), only that they're all configured to see each other via Compose which, well, is not very useful given that Compose is mostly mocking things out for a developer to use locally.

Can somebody explain to me what problem this solves that can't be better solved with more focused tests?
