### ISSUE TITLE
Fix UnhandledPromiseRejectionWarning in Vue frontend 

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#162]
## Overview
Currently, when running `docker-compose -f local.yml up vue`, the following error appears:

```bash
vue_1         |  DONE  Compiled successfully in 12582ms20:03:55
vue_1         | 
vue_1         | > Listening at http://0.0.0.0:8080
vue_1         | 
vue_1         | (node:15) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
vue_1         | (node:15) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Expected Behavior
The error should not occur.

## Technical details

- This feature should be implemented in the [`interface/frontend/src/`](https://github.com/concept-to-clinic/concept-to-clinic/tree/master/interface/frontend/src) folder.

## Acceptance criteria

 - [ ] running `docker-compose -f local.yml up vue` should exit with no errors. 

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by lamby** [comment]
Fixed! Thanks!
