### ISSUE TITLE
Keep docker container size under control

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#165]
## Overview

It appears that multiple runs of `docker-compose -f local.yml build` increase the size of the `Data` without removing stale artifacts. My current  `~/Library/Containers/com.docker.docker` folder is over 26GB. There should be a convenient script that can be run to remove all unneeded docker files.

## Expected Behavior
Running the script should remove all unneeded docker files.

## Technical details

- sample clean commands

```bash
docker ps -aqf status=exited | xargs docker rm
docker images -qf dangling=true | xargs docker rmi
```

- the clean commands should not remove the image caches

- This feature should be implemented in [`local.yml`](https://github.com/concept-to-clinic/concept-to-clinic/tree/master/local.yml)

## Acceptance criteria

 - [ ] running `docker-compose -f local.yml build` should first remove unneeded docker files

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by gilcolon71** [comment]
Hi!

I'm a data science student and I'm very interesting in this topic/solution.  Have you considered using an alpine base image?

**Comment by reubano** [comment]
Hi @gilcolon71, while switching to a smaller base image like alpine can definitely be useful, that's more of a peripheral concern. I think https://github.com/docker/for-mac/issues/371 does a better job of explaining the key issue.

**Comment by WGierke** [comment]
From [Allow compose to run arbitrary commands at the host level after or before containers are started](https://github.com/docker/compose/issues/2012):  
`command is always run in a container. docker-compose is not a tool for running commands on the host.`
Seems like we need to put your suggested commands into an extra bash script :/

**Comment by calvernaz** [comment]
This [comment](https://github.com/docker/for-mac/issues/371#issuecomment-348745353) details a solution that worked for me,  after installing docker edge on High Sierra the `Data` folder moved from 36GB to 1.4GB

**Comment by reubano** [comment]
@WGierke and @calvernaz thanks for the input! So I guess the solution is to upgrade and clean manually occasionally?

**Comment by calvernaz** [comment]
Indeed

**Comment by WGierke** [comment]
I think so, yes

**Comment by reubano** [comment]
@calvernaz and @WGierke got it. Perhaps we should update [the documentation](https://concept-to-clinic.readthedocs.io/en/latest/developing-locally-docker.html#other-notes) to include this information then.
