### ISSUE TITLE
Reduce complexity of predict_cubes

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#166]
## Overview
The [`prediction/src/algorithms/identify/prediction/predict_cubes`](https://github.com/concept-to-clinic/concept-to-clinic/blob/317b8c183a5fab3a25b87160862a2772ef2c86fe/prediction/src/algorithms/identify/prediction.py#L145-L266) function needs to be refactored to reduce its complexity.

## Acceptance criteria

 - [ ] 2 or 3 sub functions should be split off from the `predict_cubes` function

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by lamby** [comment]
Merged!
