### ISSUE TITLE
Use css preprocessor like sass, less...

### ISSUE THREAD

**Issue by truefalse10** [concept-to-clinic/concept-to-clinic#167]
The current vue.js setup allows only to write styles in pure css. This can be quite time consuming, error-prone and leads to redundant code. In order to use variables, mixins and all other handy tools I would suggest using a preprocessor. In vuejs this can be easily achieved by installing the preferred webpack [loader](https://vue-loader.vuejs.org/en/configurations/pre-processors.html). My suggestions would be to use SCSS because it has the same syntax as CSS and can therefore easily be adapted by people new to preprocessores. 

## Expected Behavior
I can write component styles with scss/sass/less/stylus and it gets compiled to css

## Current Behavior
using `<style lang="scss">` leads to compile time error

## Possible Solution
install missing webpack loaders

**Comment by WGierke** [comment]
So has this now been implemented in 11d04b0?

**Comment by calvernaz** [comment]
Exactly what is missing here?

**Comment by isms** [comment]
@lamby Can you look into this and close the issue if necessary?
