### ISSUE TITLE
Refactor prediction MetaData and PreprocessCT usage

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#169]
## Overview

[`PreprocessCT`](https://github.com/concept-to-clinic/concept-to-clinic/blob/317b8c183a5fab3a25b87160862a2772ef2c86fe/prediction/src/preprocess/preprocess_ct.py#L56-L112) and [`MetaData`](https://github.com/concept-to-clinic/concept-to-clinic/blob/317b8c183a5fab3a25b87160862a2772ef2c86fe/prediction/src/preprocess/load_ct.py#L109-L159) should to be refactored and their usage made more pythonic.

## Technical details

- `PreprocessCT` should subclass [`Params`](https://github.com/concept-to-clinic/concept-to-clinic/blob/317b8c183a5fab3a25b87160862a2772ef2c86fe/prediction/src/preprocess/preprocess_ct.py#L6-L53)
- functions/methods that need access to `MetaData` (like [`preprocess_ct`](https://github.com/concept-to-clinic/concept-to-clinic/blob/317b8c183a5fab3a25b87160862a2772ef2c86fe/prediction/src/algorithms/classify/trained_model.py#L58), [`crop_patch`](https://github.com/concept-to-clinic/concept-to-clinic/blob/317b8c183a5fab3a25b87160862a2772ef2c86fe/prediction/src/preprocess/crop_patches.py#L27-L53), [`PreprocessCT.__call__`](https://github.com/concept-to-clinic/concept-to-clinic/blob/317b8c183a5fab3a25b87160862a2772ef2c86fe/prediction/src/preprocess/preprocess_ct.py#L83-L105)) should take the output of [`load_ct`](https://github.com/concept-to-clinic/concept-to-clinic/blob/317b8c183a5fab3a25b87160862a2772ef2c86fe/prediction/src/preprocess/load_ct.py#L79-L106) as direct arguments (and internally call `MetaData`)

E.g., you should then be able to turn [`test_preprocess_dicom_clips`](https://github.com/concept-to-clinic/concept-to-clinic/blob/317b8c183a5fab3a25b87160862a2772ef2c86fe/prediction/src/tests/test_preprocess_dicom.py#L44-L49) into something like this:

```python
from prediction.src.preprocess.load_ct import load_ct
from prediction.src.preprocess.preprocess_ct import PreprocessCT


def test_preprocess_dicom_clips(dicom_path):
     preprocess = PreprocessCT(clip_lower=-1, clip_upper=40)
     dicom_array = preprocess(*load_ct(dicom_path))
     ...
```

## Acceptance criteria (in addition to the above)

 - [ ] All `*args` and `**kwargs` should be documented, and done using
 [`google style`](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)
 - [ ] All classes should be [`new style`](https://stackoverflow.com/a/1203997/408556)

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by lamby** [comment]
Thanks!
