### ISSUE TITLE
Use git-lfs for test images

### ISSUE THREAD

**Issue by pjbull** [concept-to-clinic/concept-to-clinic#17]
## Overview
Currently test images are stored in the git repository. These files won't change much so we should try to save bandwidth and separate concerns by tracking them with `git-lfs` instead.

## Expected Behavior
DICOM images in `tests/assets` are managed with `git-lfs`

## Acceptance criteria
 - [ ] test images are managed by `git-lfs`
 - [ ] large image files are removed from the repository

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by poppingtonic** [comment]
I have a public fork [here](https://github.com/poppingtonic/concept-to-clinic.git) and want to tackle this issue. I can't update my fork with the LFS data because of [this issue](https://github.com/git-lfs/git-lfs/issues/1906)

```
Git LFS: (0 of 534 files) 0 B / 268.10 MB                                                                                                              
batch response: @poppingtonic can not upload new objects to public fork poppingtonic/concept-to-clinic                                                 
batch response: @poppingtonic can not upload new objects to public fork poppingtonic/concept-to-clinic                                                 
batch response: @poppingtonic can not upload new objects to public fork poppingtonic/concept-to-clinic                                                 
batch response: @poppingtonic can not upload new objects to public fork poppingtonic/concept-to-clinic                                                 
batch response: @poppingtonic can not upload new objects to public fork poppingtonic/concept-to-clinic                                                 
batch response: @poppingtonic can not upload new objects to public fork poppingtonic/concept-to-clinic  
```

**Comment by lamby** [comment]
@poppingtonic Hey, thanks for jumping in :) I think what would be the best "next step" would be if you could get a branch / PR up and running here - that way it should smooth the permissions out, no?

**Comment by lamby** [comment]
@poppingtonic Thanks so much for this. As we can't work around the permissions I've gone ahead and done this in 7d46f083a9e3dc13042da1ffbc275d9e9b055833 and will credit you for the effort :)

**Comment by poppingtonic** [comment]
Thank you @lamby.
