### ISSUE TITLE
API actions that change database state should return updated instance data

### ISSUE THREAD

**Issue by isms** [concept-to-clinic/concept-to-clinic#178]
Examples include the `interface.backend.api.views.candidate_mark` and `interface.backend.api.views.candidate_dismiss`.

Right now they return a one-off response payload, e.g.

```python
@api_view(['GET'])
def candidate_dismiss(request, candidate_id):
    return Response({'response': "Candidate {} was dismissed".format(candidate_id)})
```

It's better for Vue usage if we instead just return the newly updated, serialized `Candidate` to be redisplayed, and the `200 OK` status code tells us we successfully updated the object.

**Comment by brycecf** [comment]
@isms Is anyone working on this and #177?  If not, I would be happy to help out.

**Comment by isms** [comment]
@brycecf Feel free! Just be aware the example given is old, so this would count for anywhere you can find endpoints that don't go along with this.

**Comment by WGierke** [comment]
@brycecf Are you still working on this one?

**Comment by isms** [comment]
@WGierke before you dive in you may just want to check the open PRs to see if any issues have already been resolved

**Comment by sirusss** [comment]
If this has not been resolved yet, I plan to make a PR this week to look into the issue.

**Comment by isms** [comment]
Closing this issue now that the Vuex pattern is being used as of #265
