### ISSUE TITLE
Vue: reusable Javascript DICOM image viewer component

### ISSUE THREAD

**Issue by isms** [concept-to-clinic/concept-to-clinic#179]
Splitting this off from #148 and #150.

### **Note:** Proofs of concept with a specific library will be in a position to receive points for this even if a different way of doing it is ultimately selected. These add value to the project by giving other contributors a reference point for how this may be done.

We need to be able to show DICOM imagery in an interactive way. There are existing libraries designed to do this:
* [Cornerstone Tools](https://github.com/chafey/cornerstoneTools) (see especially [this example](https://rawgit.com/chafey/cornerstoneTools/master/examples/freehandRoi/index.html) of drawing freehand boundaries)
* ~DICOM web viewer~ (GNU GPL v3 not compatible with MIT license)
* Others (Google shows a few more)

## Expected Behavior

Somebody needs to make these work nicely with Vue so we can show things like predicted nodule centroids (#148) and boundaries (#150) above the image slices, and also let them change centroids or mark new places. See the design doc for a discussion of features.

**Comment by isms** [comment]
@swederik Any interest in taking a crack at this?

**Comment by swederik** [comment]
I don't have the time at the moment, sorry.

**Comment by jjjmm** [comment]
@isms i could give it a try, since it is within scope of #150

**Comment by jjjmm** [comment]
@isms [DICOM web viewer](https://ivmartel.github.io/dwv/) is under GNU GPL 3 license. Does it mean, that we can't use it in this project, since it is under MIT license?

**Comment by isms** [comment]
@jjjmm Good point: GNU GPL 3 not compatible with MIT. I'll scratch that.
