### ISSUE TITLE
Add fields to `Case` and `Nodule` models based on RadReport template

### ISSUE THREAD

**Issue by isms** [concept-to-clinic/concept-to-clinic#181]
RadReport defines industry best practices for what information should be recorded on a lung cancer screen. Some are specific to the overall image series (the `Case` model) and some are specific to each nodule (the `Nodule` model).

## Expected Behavior
Appropriate new fields on appropriate models with the migrations that implement them.

## References
[1] Design doc - http://concept-to-clinic.readthedocs.io/en/latest/design-doc.html#results
[1] Rad Report template for CT Lung Cancer Screening - http://www.radreport.org/template/0000268

**Comment by lamby** [comment]
Merged in #185.. thanks!
