### ISSUE TITLE
Vue: implement results mockups under 'Report and Export' screen

### ISSUE THREAD

**Issue by isms** [concept-to-clinic/concept-to-clinic#182]
**This depends on #181 for actual database models to be updates - until then these fields can simply be mocked.**

![image](https://user-images.githubusercontent.com/1284973/31911878-eebf37a0-b7f6-11e7-89a9-87282c3432c7.png)

See design doc: http://concept-to-clinic.readthedocs.io/en/latest/design-doc.html#results

**Comment by louisgv** [comment]
I can take a look at this

**Comment by louisgv** [comment]
I can take a look a this!
