### ISSUE TITLE
Document the Daniel Hammack algorithm

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#19]
## Overview

Participants in the [Data Science Bowl](https://www.kaggle.com/c/data-science-bowl-2017) produced several algorithms that we would like to incorporate. To help facilitate this effort, we also want to add documentation so that contributors can make an educated decision when selecting an algorithm to incorporate.

## Expected Behavior

This documentation should enable people to:
 - view the library dependencies and license
 - understand its pros/cons
 - evaluate its performance/accuracy
 - identify which areas of the codebase to target for improvement

Design doc reference: [Detect and select](https://concept-to-clinic.readthedocs.io/en/latest/design-doc.html#detect-and-select)

## Algorithm info

key | value
----|------
team|Daniel Hammack
rank|1
repo|https://github.com/dhammack/DSB2017 & https://github.com/juliandewit/kaggle_ndsb2017
trained models|https://retinopaty.blob.core.windows.net/ndsb3/trained_models.rar
converted branch|
ML engine|Keras
engine-version|
ML backend|Theano
backend-version|
training method|
architecture|
algorithm|
OS|Windows
OS version|64bit
Python version|2.7 & 3.5
CUDA version|
cuDNN version|
notes|

## Technical details

 - This feature should be implemented as a new markdown file in the [`docs folder`](https://github.com/concept-to-clinic/concept-to-clinic/tree/master/docs)

## Acceptance criteria

 - [ ] effective documentation for the above

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by WGierke** [comment]
I've reached out to the author since he mentions in the README that he knows how to simplify and speed-up his code without major performance loss.

**Comment by WGierke** [comment]
Unfortunately, the author didn't respond so far. @reubano you already wrote that the code runs on Windows 64bit with Python 3.5. From where did you receive this information? I'm a bit confused because I found a lot `print` statements in the code that don't have parentheses which would throw errors when running with Python 3.

**Comment by reubano** [comment]
@wgierke turns out this one is actually a combination of two repos and it was the 2nd one that I got the info from. Thanks for pointing that out! I've since updated the description.

**Comment by WGierke** [comment]
@reubano I guess this one can be closed?

**Comment by reubano** [comment]
@wgierke nice catch!

**Comment by kmader** [comment]
Don't want to re-open a closed issue, but we are also working on getting some of the DSB models working and have forked this repository and invested some time in getting the keras1.2 model into a standard keras2 model and extracting the py2.7 code and getting it work with py3.5 (https://github.com/4Quant/DSB2017/blob/master/ApplyModel.ipynb). It is quite a hacky bit of work to extract cleanly the models from someone else's code and get everything working

**Comment by reubano** [comment]
@kmader you may want to [take a look here](https://github.com/concept-to-clinic/DSB2017/tree/conversion) for some inspiration. Also, see #4 and #122.
