### ISSUE TITLE
Correct case of links in documentation sidebar

### ISSUE THREAD

**Issue by lamby** [concept-to-clinic/concept-to-clinic#198]
On: https://concept-to-clinic.readthedocs.io/

## Current Behavior
[](https://i.imgur.com/djeE94L.jpg) (https://i.imgur.com/djeE94L.jpg)

## Expected Behavior
"Interface" and "Prediction" (ie. title case, not all lower case)

## Steps to Reproduce

1. https://concept-to-clinic.readthedocs.io
2. Scroll to bottom of navigation

## Checklist before submitting
- [ ] I have confirmed this using the officially supported Docker Compose setup using the `local.yml` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [ ] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [ ] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [ ] I provided **screenshots** where appropriate
- [ ] I filled out all the relevant sections of this template

**Comment by WGierke** [comment]
( :+1: for the first-pr-only label)
