### ISSUE TITLE
Improve open imagery "Import" button UX

### ISSUE THREAD

**Issue by lamby** [concept-to-clinic/concept-to-clinic#202]
## Current Behavior

![](https://i.imgur.com/g7P0jyI.jpg)

Pressing the *Import* button expands the filename browser. This makes sense. However, pressing *Import* again contracts the browser, which does not make much sense as you

## Expected Behavior

Unsure about the ideal behaviour. One possibility at this point is that the copy changes after it has expanded (eg. "hide import"). Alternatively, we could hide the button altogether. Or we explicitly change it to "Show files / hide files". Please experiment!

## Checklist before submitting
- [ ] I have confirmed this using the officially supported Docker Compose setup using the `local.yml` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [ ] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [ ] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [ ] I provided **screenshots** where appropriate
- [ ] I filled out all the relevant sections of this template

**Comment by louisgv** [comment]
If the allows user to import multiple image, then we should remove the call to contracts the browser from the import button event handler, and instead add it to a drop-down button element similar to what we have with nodule.

**Comment by Serhiy-Shekhovtsov** [comment]
I am not sure if we should allow selecting multiple images. In documentation we can find the following: 
> Allow user to select a given image and start a new “Case.” This image will be used in the identification step next
Also it will complicate some things, including this story: Prevent progress to next stage of analysis until "completed" the current step (#204).
Please, let me know what do you think? (This issue is blocking me with #145)

**Comment by louisgv** [comment]
@Serhiy-Shekhovtsov After reading the requirement again, I think we should separate the two function into 2 UI elements (button), one for importing image and one for expanding the image. So maybe for #145, you can simply change the callback of the import button to do what need to be done, or you can also add a new button to import (to avoid conflict with this issue), and then we can refactor the UI at a later stage?

**Comment by louisgv** [comment]
Hmm, seems like #204 and #202 (this) will be sharing some higher order state. I will do some experiment with this UI element as well as implementing a parent state (to keep track of the step for #204) then :-?

**Comment by Serhiy-Shekhovtsov** [comment]
I am going to do the following: 

- Show if there is any case started. If started - show a message that starting a new case will drop the current one. 
- Show list of images in local system. User can click on image name to view it. (this is already implemented)
- On "start case" button click - I will drop the current case and create a new one with selected image.

**Comment by Serhiy-Shekhovtsov** [comment]
@louisgv , but I already started #202. And this one looks like really minor and will be closed as well.

**Comment by Serhiy-Shekhovtsov** [comment]
@louisgv I think you can work on #204 separately, right?

**Comment by louisgv** [comment]
@Serhiy-Shekhovtsov For sure! I thought you were looking to avoid conflicting with this issue, but if you can solve both that'd be great :p I didn't mean to raise conflict/confusion.

Also I was spending the entire day updating my build... refer to #234 :skull:

**Comment by Serhiy-Shekhovtsov** [comment]
!["Import" button UX](http://g.recordit.co/QvlvS3OCv6.gif)

**Comment by isms** [comment]
Closed as of #265
