### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by lamby** [concept-to-clinic/concept-to-clinic#203]
## Current Behavior

```
Traceback (most recent call last):
  File "/app/src/factory.py", line 53, in <module>
    app = create_app()
  File "/app/src/factory.py", line 36, in create_app
    from .views import blueprint
  File "/app/src/views.py", line 9, in <module>
    from .algorithms.classify import trained_model as classify_trained_model
  File "/app/src/algorithms/classify/trained_model.py", line 10, in <module>
    from src.algorithms.classify.src import gtr123_model
ModuleNotFoundError: No module named 'src'
```

## Steps to Reproduce
1. Visit http://localhost:8001/
2. See traceback

## Checklist before submitting
- [ ] I have confirmed this using the officially supported Docker Compose setup using the `local.yml` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [ ] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [ ] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [ ] I provided **screenshots** where appropriate
- [ ] I filled out all the relevant sections of this template

**Comment by reubano** [comment]
FYI, here's how it was [previously fixed](https://github.com/concept-to-clinic/concept-to-clinic/commit/a482fd890af5ef81c088464f619c8a427e2199ea)
