### ISSUE TITLE
Prevent progress to next stage of analysis until "completed" the current step

### ISSUE THREAD

**Issue by lamby** [concept-to-clinic/concept-to-clinic#204]
## Expected Behavior
The interface should prevent you from moving to the next stage of the image analysis until you have completed the current step, whatever that means for each step.

## Current Behavior
You can proceed to, for example, "Annotate and segment" wthout importing any images.

## Checklist before submitting
- [ ] I have confirmed this using the officially supported Docker Compose setup using the `local.yml` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [ ] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [ ] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [ ] I provided **screenshots** where appropriate
- [ ] I filled out all the relevant sections of this template

**Comment by louisgv** [comment]
Will be thinking about a good practice solution for this.

**Comment by louisgv** [comment]
If nobody has working on this yet, I will begin tomorrow.

**Comment by louisgv** [comment]
So I think since each tab are controlled by vue-router, the solution to this would be to add a gate layer to each route and check for condition. 

https://router.vuejs.org/en/advanced/navigation-guards.html

Will be going through the doc and implement a simple gate layer for each route.
