### ISSUE TITLE
Export PDF functionality

### ISSUE THREAD

**Issue by lamby** [concept-to-clinic/concept-to-clinic#205]
![](https://i.imgur.com/qzuzIKD.jpg)

## Expected Behavior
Pressing *Export* exports the page as a PDF

## Current Behavior
(Not implemented)

## Checklist before submitting
- [ ] I have confirmed this using the officially supported Docker Compose setup using the `local.yml` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [ ] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [ ] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [ ] I provided **screenshots** where appropriate
- [ ] I filled out all the relevant sections of this template

**Comment by Serhiy-Shekhovtsov** [comment]
@lamby,  I can see the **interface-backend** tag, is there a particular reason why this has to be done on the server side? I am asking this, cause implementing it on the client side should be an easy task.

**Comment by lamby** [comment]
@Serhiy-Shekhovtsov Implementing client-side is fine :)
