### ISSUE TITLE
Factor out EXTRACTED_IMAGE_DIR

### ISSUE THREAD

**Issue by lamby** [concept-to-clinic/concept-to-clinic#208]
We use ``EXTRACTED_IMAGE_DIR`` in a few places in the code, eg in prediction/src/algorithms/identify/prediction.py:

```
21:EXTRACTED_IMAGE_DIR = "data/extracted/"
```
This should be factored out into a more suitable location (eg. a setting or configuration - see elsewhere for prior art).

It should also use ``os.path.join`` for extra bonus points!

## Checklist before submitting
- [ ] I have confirmed this using the officially supported Docker Compose setup using the `local.yml` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [ ] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [ ] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [ ] I provided **screenshots** where appropriate
- [ ] I filled out all the relevant sections of this template

**Comment by k1703** [comment]
Hi,

Could I work on this one? This is my first issue here.

Thanks
