### ISSUE TITLE
Fix docker-compose build error

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#222]
## Overview

Building any docker service fails with the following

```bash
⚡ docker-compose -f local.yml build
...
Building prediction
Step 1/2 : FROM concepttoclinic_base
ERROR: Service 'prediction' failed to build: pull access denied for concepttoclinic_base, repository does not exist or may require 'docker login'
```

## Expected Behavior

Services should build without error

## Acceptance criteria

 - [ ] `docker-compose -f local.yml build` should complete without error. 
 - [ ] `docker-compose -f local.yml build prediction` should complete without error. 

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by WGierke** [comment]
Can you give us the output of `docker images | grep concepttoclinic_base` ? I think the base image might get another name at your computer (since it works on Travis).

**Comment by reubano** [comment]
```bash
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alcf_base           latest              ab2fe956c2de        2 days ago          3.14GB
ubuntu              rolling             79dbcfa8f169        8 days ago          93.8MB
```

Changing the dockerfile to `FROM alcf_base` did the trick, thanks! Guess it goes by the name of the project folder.

**Comment by WGierke** [comment]
Good to hear that it works now :)

**Comment by reubano** [comment]
So is this something that can be set dynamically? Or should we have a disclaimer somewhere that telling people what to do if they encounter this error?

**Comment by WGierke** [comment]
Setting the image name automatically would be the cleanest solution IMO. [SO](https://stackoverflow.com/questions/32230577/how-do-i-define-the-name-of-image-built-with-docker-compose) says `docker-compose --project-name foo build bar` would build the image foo_bar no matter what the parent directory is named. [This answer](https://stackoverflow.com/questions/32230577/how-do-i-define-the-name-of-image-built-with-docker-compose/33951705#33951705) even shows how to do that using the docker-compose YAML file.
