### ISSUE TITLE
Fix interface building

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#227]
## Overview

Building the interface service fails with the following error

```bash
⚡ docker-compose -f local.yml build interface
...
Step 3/9 : RUN sed -i 's/\r//' /entrypoint.sh
 ---> Running in 4e5814af28da
container_linux.go:265: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
ERROR: compose.cli.main.main: Service 'interface' failed to build: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
```

## Expected Behavior

Interface services should build without error

## Technical details

- This bug first appears in #199 
- Possibly related to https://github.com/moby/moby/issues/5135
- Possibly specific to Docker For Mac 
- Docker For Mac v17.09.0-ce-mac35
- macOS 10.13

```
$ docker --version
Docker version 17.09.0-ce, build afdb6d4
```

## Acceptance criteria

 - [ ] `docker-compose -f local.yml build` should complete without error. 
 - [ ] `docker-compose -f local.yml build interface` should complete without error. 

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by musale** [comment]
@reubano interestingly, I've done the build without any errors from the current master branch.
**OS** : Manjaro Linux
**Docker version**: 17.10.0-ce, build f4ffd2511c

My suggestion would be you try with upgraded docker?

**Comment by reubano** [comment]
Ok, so I tried it again and now everything works! Turns out the [solution I implemented](https://github.com/docker/for-mac/issues/1396#issuecomment-313457823) to solve another problem, ending up fixing this one as well. Thanks!
