### ISSUE TITLE
Docker Build failed, /proc file permission denied

### ISSUE THREAD

**Issue by louisgv** [concept-to-clinic/concept-to-clinic#234]
## Expected Behavior

Upon pulling new change from master, I should be able to run `docker-compose -f local.yml build` to update the docker image.

## Current Behavior

The build process failed:

```
Step 8/21 : RUN find . -type d -name __pycache__ -exec rm -r {} \+
 ---> Running in 41c5736fc3df
find: './proc/1/map_files': Operation not permitted
find: './proc/7/map_files': Operation not permitted
ERROR: Service 'base' failed to build: The command '/bin/sh -c find . -type d -name __pycache__ -exec rm -r {} \+' returned a non-zero code: 1
```
## Steps to Reproduce

1. Pull from master
2. Run `docker-compose -f local.yml build`

## Context (Environment)

This might be specific to Debian. My operating system is:
```
Linux lab 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u3 (2017-08-15) x86_64 GNU/Linux
```

## Checklist before submitting
- [x] I have confirmed this using the officially supported Docker Compose setup using the `local.yml` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [x] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [ ] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [ ] I provided **screenshots** where appropriate
- [ ] I filled out all the relevant sections of this template

**Comment by louisgv** [comment]
After spending an entire day trying all kind of thing to fix the problem, from reinstalling docker, to remove docker tunnel, to reboot my machine a dozen of time, I decided to just comment out the 8th docker command in the `base` instruction, and that solved the problem.

This was super frustrating. But I think this line should be investigated and might need improvement:

```
RUN find . -type d -name __pycache__ -exec rm -r {} \+
```

Maybe we can use a python package like pyclean or py3clean to clean up the cache instead of searching for it manually?

**Comment by reubano** [comment]
I can't reproduce this, but it could be related to https://github.com/moby/moby/issues/16506. Perhaps a PR blacklisting the `proc` dir may help.

**Comment by reubano** [comment]
> Maybe we can use a python package like pyclean or py3clean to clean up the cache instead of searching for it manually?

FYI, these packages do the same thing as the script. Just in python instead of bash.

**Comment by isms** [comment]
@louisgv I think it's time to close this and #238 unless you can update us with current status and detailed steps to reproduce. Thoughts?

**Comment by louisgv** [comment]
@isms let's close this for now. By commenting out the 8th line of the docker script this problem is gone for me.
