### ISSUE TITLE
Update that version number in the Navbar

### ISSUE THREAD

**Issue by pjbull** [concept-to-clinic/concept-to-clinic#244]
## Expected Behavior
Navbar has short git hash that matches the current version of the code. This will be especially valuable on the [demo site](http://demo.concepttoclinic.drivendata.org).

## Current Behavior
Nav bar displays the string `a0b1c2d` all the time.

<img width="1000" alt="screen shot 2017-11-21 at 11 46 32 am" src="https://user-images.githubusercontent.com/1799186/33101365-eba44e06-cecc-11e7-9b3c-9d1370eecbcb.png">

## Steps to Reproduce
1. Run the application UI

## Possible Implementation
 - Get short git hash in the [backend Dockerfile](https://github.com/concept-to-clinic/concept-to-clinic/blob/master/compose/interface/Dockerfile-dev-api)
 - Export to `GIT_HASH_VERSION` env variable in Dockerfile (so that it is evaluated _at container build time_)
 - Get that env variable within the backend settings
 - Return that setting value through an endpoint (actually, maybe through all of them?)
 - Call that [endpoint in the frontend navbar](https://github.com/concept-to-clinic/concept-to-clinic/blob/master/interface/frontend/src/components/AppNav.vue) to get the right data

**Comment by lamby** [comment]
Merged in https://github.com/concept-to-clinic/concept-to-clinic/commit/615261c5cebf040dc971fd212b161c7fbd1055d1 :)

**Comment by WGierke** [comment]
@lamby can this issue be closed then?
