### ISSUE TITLE
Refactor Front-end Unit Test Suite

### ISSUE THREAD

**Issue by louisgv** [concept-to-clinic/concept-to-clinic#245]
## Expected Behavior

Front-end should have a run-able unit test suite so that we can validate new component/works.

## Current Behavior

The current unit test suite does not run and it is using deprecated packages. It also does not setup to run on docker.

## Possible Solution

+ Adding docker build
+ Upgrade test tool dependency or switch to better tool.

## Steps to Reproduce

1. There is no way to run front-end test at the moment.

## Checklist before submitting
- [x] I have confirmed this using the officially supported Docker Compose setup using the `local.yml` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [x] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [x] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [x] I provided **screenshots** where appropriate
- [x] I filled out all the relevant sections of this template

**Comment by louisgv** [comment]
Work on this has already been started and will be published in #239

**Comment by lamby** [comment]
Fixed in https://github.com/concept-to-clinic/concept-to-clinic/commit/09d4bc5863f2fcf7e166d4b15cef01779a8b8dd4
