### ISSUE TITLE
Refactor Front-end E2E Test Suite

### ISSUE THREAD

**Issue by louisgv** [concept-to-clinic/concept-to-clinic#246]
## Expected Behavior

One should be able to run the E2E from a docker environment and see the result.

## Current Behavior

The current test suite does not run in a docker environment due to its reliant on node to build and expose selenium, which in turn is relying on a system-wide JAVA installation.

## Possible Solution

Purge local installation of chromedriver and selenium, and instead use docker to install these tool so that we can use them on a docker environment.

## Steps to Reproduce

1. None of the test is working on Docker

## Checklist before submitting
- [x] I have confirmed this using the officially supported Docker Compose setup using the `local.yml` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [x] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [x] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [x] I provided **screenshots** where appropriate
- [x] I filled out all the relevant sections of this template

**Comment by louisgv** [comment]
Work on this has already been started and will be published together with #239

**Comment by lamby** [comment]
Fixed in https://github.com/concept-to-clinic/concept-to-clinic/commit/09d4bc5863f2fcf7e166d4b15cef01779a8b8dd4
