### ISSUE TITLE
Document the DL Munich algorithm

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#25]
## Overview

Participants in the [Data Science Bowl](https://www.kaggle.com/c/data-science-bowl-2017) produced several algorithms that we would like to incorporate. To help facilitate this effort, we also want to add documentation so that contributors can make an educated decision when selecting an algorithm to incorporate.

## Expected Behavior

This documentation should enable people to:
 - view the library dependencies and license
 - understand its pros/cons
 - evaluate its performance/accuracy
 - identify which areas of the codebase to target for improvement

Design doc reference: [Detect and select](https://concept-to-clinic.readthedocs.io/en/latest/design-doc.html#detect-and-select)

## Algorithm info

key | value
----|------
team|DL Munich
rank|7
repo|https://github.com/NDKoehler/DataScienceBowl2017_7th_place
trained models|requested
converted branch|
ML engine|
engine-version|
ML backend|Tensorflow
backend-version|1.0.1
training method|
architecture|
algorithm|
OS|Ubuntu
OS version|14.04
Python version|
CUDA version|
cuDNN version|
notes|

## Technical details

 - This feature should be implemented as a new markdown file in the [`docs folder`](https://github.com/concept-to-clinic/concept-to-clinic/tree/master/docs)

## Acceptance criteria

 - [ ] effective documentation for the above

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by vessemer** [comment]
Is there something else left that prevents this issue from getting closed?

**Comment by reubano** [comment]
nope... thanks for the reminder
