### ISSUE TITLE
Document the Alex |Andre |Gilberto |Shize algorithm

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#26]
## Overview

Participants in the [Data Science Bowl](https://www.kaggle.com/c/data-science-bowl-2017) produced several algorithms that we would like to incorporate. To help facilitate this effort, we also want to add documentation so that contributors can make an educated decision when selecting an algorithm to incorporate.

## Expected Behavior

This documentation should enable people to:
 - view the library dependencies and license
 - understand its pros/cons
 - evaluate its performance/accuracy
 - identify which areas of the codebase to target for improvement

Design doc reference: [Detect and select](https://concept-to-clinic.readthedocs.io/en/latest/design-doc.html#detect-and-select)

## Algorithm info

key | value
----|------
team|Alex &#124;Andre &#124;Gilberto &#124;Shize
rank|8
repo|https://github.com/astoc/kaggle_dsb2017
trained models|https://github.com/astoc/kaggle_dsb2017/tree/master/code/Andre/nodule_identifiers
converted branch|
ML engine|Keras
engine-version|1.2.2
ML backend|Theano
backend-version|
training method|
architecture|
algorithm|
OS|
OS version|
Python version|
CUDA version|
cuDNN version|
notes|

## Technical details

 - This feature should be implemented as a new markdown file in the [`docs folder`](https://github.com/concept-to-clinic/concept-to-clinic/tree/master/docs)

## Acceptance criteria

 - [ ] effective documentation for the above

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by tjvananne** [comment]
I'm reading through this one right now. Please correct me if I'm wrong, but it seems like the competition target variable was to predict the **probability of the patient having cancer** as a whole as opposed to the probability of each individual nodule within the lungs? 

It looks like most of these go through the same z-slice normalization, lung segmentation, and nodule detection/isolation steps. But then it's the final feature generation steps that might need to be refactored quite a bit to tackle the new problem statement of predicting the **probability of each nodule being cancerous**. Is that a fair statement?

A feature such as `total_number_of_nodules` (I made that up as an example) aggregated at the patient level might still be important at the nodule level, but it does seem to imply that the goal was slightly different.

**Comment by reubano** [comment]
Answer [posted here](https://github.com/concept-to-clinic/concept-to-clinic/issues/58#issuecomment-323731643).

**Comment by lamby** [comment]
@tjvananne Did @reubano's link answer your question? :)

**Comment by WGierke** [comment]
@lamby same here - is something preventing this issue from getting closed? :)
