### ISSUE TITLE
UI state isn't preserved across tab navigations

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#264]
## Overview

If you select a DICOM file from the "Open Image" tab and navigate to another tab, once you return back to "Open Image", the "Import image series" panel will be gone.

![window 2017-11-28 at 14 02 03](https://user-images.githubusercontent.com/157864/33681026-005f08fa-da89-11e7-8301-ff6b96b8a603.png)
![window 2017-11-28 at 14 02 13](https://user-images.githubusercontent.com/157864/33681027-007e3716-da89-11e7-9b7b-fb49d72a6bd0.png)
![window 2017-11-28 at 14 02 17](https://user-images.githubusercontent.com/157864/33681028-00a10e3a-da89-11e7-854f-e47578b72aef.png)

## Expected Behavior

The previous state of the "Open Image" (or any) tab should be preserved, so that navigating away and then back to the same tab has no effect on the original tab's visual layout.

## Current Behavior

The original tab's visual layout resets to the default "empty" state.

## Steps to Reproduce

```bash
docker-compose -f local.yml build
docker-compose -f local.yml up
open http://localhost:8080
# navigate to a file in a DICOM file so that you see its image
# navigate to another tab
# return back to the "Open Image" tab
# notice that the screen no longer shows the DICOM image or file browser
```

## Acceptance criteria 

 - [ ] The UI state of each tab should be preserved such that clicking away and then returning to any tab should not affect the original tab's visual layout

NOTE: All PRs must follow the standard PR checklist

**Comment by isms** [comment]
Closed as of #263.
