### ISSUE TITLE
Code quality: adding docstrings (for points!)

### ISSUE THREAD

**Issue by isms** [concept-to-clinic/concept-to-clinic#274]
Go through and add docstrings or improve existing docstrings where helpful.

<hr>

*Points will be awarded continuously through the end of the competition -- this issue will not close.*

**Comment by WGierke** [comment]
Can we agree on a common [docstring format](https://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format)?

**Comment by isms** [comment]
Google or Numpy are both fine as long as they conform to the respective specification.

**Comment by lamby** [comment]
Merged! :)
