### ISSUE TITLE
Annotation: per-nodule notes should actually be PATCHed and saved

### ISSUE THREAD

**Issue by isms** [concept-to-clinic/concept-to-clinic#280]
## Expected Behavior
Manipulating these should be `PATCH`ed to the backend and saved in the appropriate model instance:
![image](https://user-images.githubusercontent.com/1284973/34627406-6c2f62a2-f22e-11e7-8b47-52c6b6ec5a5a.png)

## Current Behavior
No-op

**Comment by Serhiy-Shekhovtsov** [comment]
I'd like to take this one.

**Comment by Serhiy-Shekhovtsov** [comment]
@isms, I can see that we are using `PATCH` for updating the candidate. Is there a reason for using `POST` here?

**Comment by isms** [comment]
@Serhiy-Shekhovtsov no, not at all, PATCH is the right verb 👍

**Comment by isms** [comment]
(issue updated to say PATCH - thanks Serhiy)

**Comment by Serhiy-Shekhovtsov** [comment]
@isms the issue is solved in PR #286
