### ISSUE TITLE
Display metadata about an image prior to selection

### ISSUE THREAD

**Issue by lamby** [concept-to-clinic/concept-to-clinic#33]
## Overview

When browsing for an test case to analyse, it would be very helpful for the end-user to be able to preview a particular case before proceeding to the next step. This would also provide means to ensure and double-check they are selecting the correct patient.

We should therefore display metadata about an image prior to selection.

## Expected Behavior

The image metadata should be displayed in a panel on the right-hand side of the interface. For example:

![](https://i.imgur.com/RPBh9wt.jpg)

## Technical details

Upon clicking on an image file, the data will have to be loaded. A preview of the image will need to be displayed too, likely in a seperate HTTP call, but it may be possible and cleaner to provide a preview within the same payload by base64-encoding the image data.

## Acceptance criteria

A pane on the right-hand side of the open image will reveal all the relevant metadata for an image.

## Blocked by
Issues: #9

**Comment by WGierke** [comment]
Do you know what the "mA" (probably milliampere?) information means and how to access it using `pydicom`?

**Comment by WGierke** [comment]
@lamby friendly ping :)

**Comment by lamby** [comment]
Fixed in #117!
