### ISSUE TITLE
Add default githooks for tests and flake8

### ISSUE THREAD

**Issue by pjbull** [concept-to-clinic/concept-to-clinic#42]
## Overview
Git hooks are useful tools that run commands before you commit

## Expected Behavior
We should have a default githook script and instructions on how to install the git hook.

## Technical details
- Add `.githook-pre-commit` file with the script to run the tests (`tests/test-docker.sh`) and flake 8 on both of the codebases.
 - Add instructions for the docs about how to copy this file to the right place and rename it so that the hooks execute before a commit.

## Acceptance criteria
- [ ] Working githooks with tests and flake8
- [ ] Documentation for the githooks

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by WGierke** [comment]
I guess this can be closed as it was implemented in #51 ?

**Comment by lamby** [comment]
Indeed, closing. Thanks @WGierke !
