### ISSUE TITLE
Fix broken links in main documentation

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#52]
## Overview

A few links in the [Getting Started section](https://concept-to-clinic.readthedocs.io/en/latest/contribute.html#getting-started) of the documentation are broken (the 2nd and 3rd bullets).

## Expected Behavior

The links found at 

- Find an open issue you’re interested in working on
- Get your local environment running with the developer documentation

should point to valid urls. 

## Acceptance criteria

 - [ ] the links no longer return 404 pages, and instead point to the intended pages.

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by WGierke** [comment]
I guess this can be closed as it was implemented in #53 ?
