### ISSUE TITLE
140MB fresh repo size (without much code or data, not using LFS)

### ISSUE THREAD

**Issue by WGierke** [concept-to-clinic/concept-to-clinic#59]
## Expected Behavior
After cloning using Git (and without LFS), after 30 commits and without test data, the repository should only be at most a few MB in size.

## Current Behavior
It's over 140 MB when cloning the master.
![screenshot from 2017-08-20 23-47-45](https://user-images.githubusercontent.com/6676439/29498742-5ce78358-8602-11e7-9b94-68c28be6a7b4.png)

## Possible Solution
I guess that the reason is that in the beginning even big files were pushed using Git. When they were then transferred to Git LFS, they weren't removed from the "normal" Git history.

## Steps to Reproduce
1. Clone the repository
2. Check its size (including hidden folders such as .git)

## Possible Implementation
Would it be possible to remove those big files from the history using references like [Removing sensitive data from a repository](https://help.github.com/articles/removing-sensitive-data-from-a-repository/) or [How to remove/delete a large file from commit history in Git repository?](https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository)? Unfortunately, I'm not that familiar with LFS or history rewriting...

## Checklist before submitting
- [X] I have confirmed this using the officially supported Docker Compose setup using the `local.py` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [X] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [X] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [X] I provided **screenshots** where appropriate
- [X] I filled out all the relevant sections of this template

**Comment by reubano** [comment]
Tagging this as official

**Comment by pjbull** [comment]
@lamby I think we may need to rewrite history to reduce this size. Can you take the lead on:
 (1) seeing if that would work
 (2) making sure the history rewrite won't majorly mess up people's existing forks/PRs (?)

**Comment by isms** [comment]
Considering closing this issue - it's a data-intensive development environment in the best case so this doesn't seem to be blocking anything. Thoughts?
