### ISSUE TITLE
Cannot view the Travis CI logs

### ISSUE THREAD

**Issue by lamby** [concept-to-clinic/concept-to-clinic#68]
Via https://github.com/concept-to-clinic/concept-to-clinic/pull/65#issuecomment-324301086

@reiinakano wrote:

> Also, I can't seem to see the Travis CI log. This would be helpful so I can see what tests failed (if there are any). Since this is a public repo anyway, why not make the CI logs public as well?

**Comment by isms** [comment]
@lamby duplicate of #63

**Comment by reiinakano** [comment]
@lamby This has already been fixed. Although there is a new issue stemming from this at #69

**Comment by lamby** [comment]
Okay, closing this in "favour" of #69. Thanks all!
