### ISSUE TITLE
Travis CI tests failing at `git clone`

### ISSUE THREAD

**Issue by reiinakano** [concept-to-clinic/concept-to-clinic#69]
## Expected Behavior
Travis CI tests shouldn't fail at the `git clone` step

## Current Behavior
This error happens during downloading of .dcm files by the Travis server at the 

`$ git clone --depth=50 https://github.com/concept-to-clinic/concept-to-clinic.git concept-to-clinic/concept-to-clinic` 

step.

```
Error downloading object: tests/assets/test_image_data/full/LIDC-IDRI-0001/1.3.6.1.4.1.14519.5.2.1.6279.6001.298806137288633453246975630178/1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192/000101.dcm (75aa4c8): Smudge error: Error downloading tests/assets/test_image_data/full/LIDC-IDRI-0001/1.3.6.1.4.1.14519.5.2.1.6279.6001.298806137288633453246975630178/1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192/000101.dcm (75aa4c8288eb31e7f6a40b8103019f664cfdd4e5b80e7a1e5d3d842c65cecfa5): batch response: Rate limit exceeded: https://github.com/concept-to-clinic/concept-to-clinic.git/info/lfs/objects/batch

Errors logged to /home/travis/build/concept-to-clinic/concept-to-clinic/.git/lfs/objects/logs/20170824T153416.634441969.log

Use `git lfs logs last` to view the log.

error: external filter 'git-lfs filter-process' failed

fatal: tests/assets/test_image_data/full/LIDC-IDRI-0001/1.3.6.1.4.1.14519.5.2.1.6279.6001.298806137288633453246975630178/1.3.6.1.4.1.14519.5.2.1.6279.6001.179049373636438705059720603192/000101.dcm: smudge filter lfs failed

warning: Clone succeeded, but checkout failed.

You can inspect what was checked out with 'git status'

and retry the checkout with 'git checkout -f HEAD'

The command "eval git clone --depth=50 https://github.com/concept-to-clinic/concept-to-clinic.git concept-to-clinic/concept-to-clinic " failed. Retrying, 2 of 3.

fatal: destination path 'concept-to-clinic/concept-to-clinic' already exists and is not an empty directory.

The command "eval git clone --depth=50 https://github.com/concept-to-clinic/concept-to-clinic.git concept-to-clinic/concept-to-clinic " failed. Retrying, 3 of 3.

fatal: destination path 'concept-to-clinic/concept-to-clinic' already exists and is not an empty directory.

The command "eval git clone --depth=50 https://github.com/concept-to-clinic/concept-to-clinic.git concept-to-clinic/concept-to-clinic " failed 3 times.

The command "git clone --depth=50 https://github.com/concept-to-clinic/concept-to-clinic.git concept-to-clinic/concept-to-clinic" failed and exited with 128 during .

Your build has been stopped.

```

## Possible Solution

Can't help here, not familiar with LFS

## Steps to Reproduce

1. Trigger a build by submitting a PR

Link to example build:
https://travis-ci.org/concept-to-clinic/concept-to-clinic/builds/268024624?utm_source=github_status&utm_medium=notification

## Context (Environment)

Can't get my PRs to be green because of this.

## Checklist before submitting
- [ ] I have confirmed this using the officially supported Docker Compose setup using the `local.py` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [x] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [x] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [ ] I provided **screenshots** where appropriate
- [x] I filled out all the relevant sections of this template

**Comment by pjbull** [comment]
Chiming in here with the thought that #59 might be part of this issue. I think we'll have to do some history rewriting there to get the DICOM images out of `git` for good, and then after that I think that we can ensure `git lfs` is turned off for travis so that we don't try to pull anything down.

IIRC, we don't need any of the `git lfs` files for the travis builds.

**Comment by pjbull** [comment]
I'm going to see if turning off `git-lfs` on Travis will fix this, thanks for the report!

**Comment by isms** [comment]
Appears to be closed by 600b307.

Thank you to @iriberri and the Travis team for looking into this. Technical background for posterity:

> I've been investigating this error and it looks like GitHub is rate-limiting the Git-LFS requests during the git clone process. I believe that this problem is surfacing after switching your project to our Open Source infrastructure because, for private projects, git clone requests are authenticated whereas for public projects these aren't. This is causing Travis CI to hit the GitHub's API rate limit for unauthenticated requests while fetching your git-lfs files.
> 
> Unfortunately, this initial `git clone` is automatically performed by Travis CI and it's not possible at the moment to make these requests to be authenticated through the .travis.yml file.
> 
> Taking this into consideration, and to sort this out, my recommendation would be to skip fetching the git-lfs files during the initial `git clone`, and then configure the authentication with GitHub and download these assets during the `before_install` phase of your build. To achieve this, you can use the following configuration:
> 
> git:
>   lfs_skip_smudge: true
> 
> before_install:
> - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
> - git lfs pull
> 
> where GITHUB_TOKEN is the GitHub token which you can generate here: > https://github.com/settings/tokens/new and then encrypt in an environment variable.

**Comment by reiinakano** [comment]
Tests are still failing from the same error.

**Comment by isms** [comment]
> EDIT: Nvm just realized people should rebase onto the latest commit first.

:smile:

**Comment by iriberri** [comment]
Glad to hear this helped!

As a bit more information, and related to https://github.com/concept-to-clinic/concept-to-clinic/issues/69#issuecomment-324764725, if you don't need these git-lfs files during build time, it'd just be enough to add the following to your .travis.yml to tell Travis not to fetch these assets during `git clone`:

```
git:
  lfs_skip_smudge: true
```
