### ISSUE TITLE
New API endpoint to fetch dataset directory

### ISSUE THREAD

**Issue by rahit** [concept-to-clinic/concept-to-clinic#77]
As per discussion in issue #31 we need a separate endpoint to fetch dataset containing images and directories.

## Expected Behavior
API call should return a list of directories and images of the dataset without preloading the dataset into the database.

## Current Behavior
Currently, homepage is making API call to `/api/images/` which is actually a ModelViewSet connected with a database model.

## Possible Solution
A completely separate endpoint needed to be called on load to fetch directory listing. This endpoint will later look into specific server directory and return the list in alphabetical order as mentioned in #31 .

## Detailed Description
Current API call in index page retrieving image list from `/api/images/` which is using magic method of Django REST frameworks's `ModelViewSet` to list down all ImageSeries object. Since `ImageSeries` is a database model, at first the files needed to be loaded into database to instantiate that way.

On the other hand, to load files directly from the filesystem, we should use Django's `storage` class as it is mentioned in #31 . This is why we need to use different API endpoint to retrieve files from storage.

## Possible Implementation
This issue will only introduce a new API endpoint. Further implementation will be tracked in #31 

## Acceptance criteria
- [ ] Update routes
- [ ] Declare view (Not implementation)
- [ ] Update `index.html` API call

**Comment by lamby** [comment]
Fixed in #81
