### ISSUE TITLE
Gloabl JS Error Handler

### ISSUE THREAD

**Issue by WGierke** [concept-to-clinic/concept-to-clinic#86]
From [PR #85 ](https://github.com/concept-to-clinic/concept-to-clinic/pull/85#pullrequestreview-60289138): build a global JS error handler that displays a notification on any passed error.

## Expected Behavior
There's one global error handler that is used as an error callback by JS functions and that displays the errors as "some kind of drop-down".

## Current Behavior
Every JS function has to implement its function that handles errors.

## Detailed Description
One example is `fetchData()` in `open_image.html`. Adding another method would mean to implement an error handler that should do the same thing as the one in `fetchData()`. According to the DRY principle, this logic should be moved into one component that is globally accessible.

## Possible Implementation
For displaying the errors, something like [bootstrap-notify](http://bootstrap-notify.remabledesigns.com/) could be used.

## Acceptance criteria
- [ ] the error handler can be invoked by scripts on different pages
- [ ] it displays the error (and optimally vanishes again without any user interaction)

**Comment by isms** [comment]
I don't think this is a best practice. The Vue way to handle this would be to have an error notification component that only shows up when there is an error message in some given piece of state.

Closing.
