### ISSUE TITLE
Layout base Django template to match wireframes

### ISSUE THREAD

**Issue by isms** [concept-to-clinic/concept-to-clinic#9]
## Overview
Even though the backend pieces have yet to be written, it will be helpful to get a mocked out frontend version quickly. Small issues exist for many of the individual UI pieces, but first the overall layout has to be created.

We want [DRY](http://wiki.c2.com/?DontRepeatYourself) templates, so we need a base template that gives the rough Bootstrap layout (e.g. navbar, breadcrumbs, main div, left pane, main pane).

## Expected Behavior
Closing this issue shouldn't implement the individual UI pieces.

In fact, many pieces of these pages will end up being refactored into individual Vue components in order to do dynamic front-endy things, so it's most important at this point to lay out some semantically correct HTML5 that others can build upon.

Design doc reference:
[[1](http://concept-to-clinic.readthedocs.io/en/latest/design-doc.html#imagery-selection)] Open imagery
[[2](http://concept-to-clinic.readthedocs.io/en/latest/design-doc.html#detect-and-select)] Detect and select
[[3](http://concept-to-clinic.readthedocs.io/en/latest/design-doc.html#annotate
)],[[4](http://concept-to-clinic.readthedocs.io/en/latest/design-doc.html#segment
)] Annotate and segment
[[5](http://concept-to-clinic.readthedocs.io/en/latest/design-doc.html#results
)] Report and export

## Technical details
- Use Bootstrap v4 (alpha)
- Create a base template that these will all inherit from and use one HTML page per wireframe image -- see the current stub at `interface/frontend/index.html` as a starting point
- Use the breadcrumbs to link from each page to the others (for now)
- **URLs do not need to work, you can use `href="#"` for now**

## Acceptance criteria
- [ ] Page more or less matches the wireframe, or uses sensible, idiomatic Bootstrap v4 UI elements
- [ ] Smoke tests ensure that each page can be loaded

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by excalliburbd** [comment]
Since Bootstrap 4 hit beta is it safe to assume we are using that instead?

**Comment by isms** [comment]
@excalliburbd Yep, v4
