### ISSUE TITLE
Replace the git LFS files in the small test image dataset with local files

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#91]
## Overview

Currently, the test image data is split into a set of large and [small](https://github.com/concept-to-clinic/concept-to-clinic/tree/master/tests/assets/test_image_data/small) [DICOM](https://en.wikipedia.org/wiki/DICOM) files. While both sets are managed by [git LFS](https://git-lfs.github.com/), we would like to convert the small data set into locally stored files so that `git-lfs` won't be required to view sample data.

## Expected Behavior

The `test_image_data/small` DICOM files are available without the need for `git-lfs`.

## Technical details

This is a continuation of #57, which created the small test data. @tdraebing provided some ideas for [removing git-lfs here](https://github.com/concept-to-clinic/concept-to-clinic/pull/57#issuecomment-325372779).

## Acceptance criteria

 - [ ] the small test image set is locally available (without `git-lfs`)
 - [ ] the tests suite passes with the reduced image dataset

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by Serhiy-Shekhovtsov** [comment]
I will take it.
