### ISSUE TITLE
Double requirement given (sphinx_rtd_theme==0.2.4 and sphinx_rtd_theme==0.1.9)

### ISSUE THREAD

**Issue by eltonlaw** [concept-to-clinic/concept-to-clinic#96]
## Detailed Description

When running `pip install -r requirements.txt` I get the following issue:

```
Double requirement given: sphinx_rtd_theme==0.2.4 (from -r requirements.txt (line 7)) (already in sphinx_rtd_theme==0.1.9 (from -r prediction/requirements/local.txt (line 6)), name='sphinx-rtd-theme')
```
This stems from the [master `requirements.txt`](https://github.com/concept-to-clinic/concept-to-clinic/blob/master/requirements.txt) file specifying `sphinx_rtd_theme==0.2.4` in line 7 and the file in [`prediction/requirements/local.txt` specifying `sphinx_rtd_theme==0.1.9`](https://github.com/concept-to-clinic/concept-to-clinic/blob/master/prediction/requirements/local.txt) in line 6. Is this on purpose, or should we update/delete the line in `prediction/requirements/local.txt`?

## Steps to Reproduce

I actually can't seem to reproduce this bug, I don't remember the steps I ran to get the error, I tried using a fresh virtualenv and pip installing with the `--no-cache` flag but no good it ran smoothly...so the severity of this issue is minuscule I guess, just a problem of keeping the dependencies aligned in the two requirements.txt files

But I can at least show that line 6 in `prediction/requirements/local.txt` doesn't actually do anything, only version 0.2.4 gets installed. Here's the successfully installed message for pip:

```
Successfully installed Django-1.11.3 Faker-0.8.3 Flask-0.12.2 Jinja2-2.9.6 MarkupSafe-1.0 appnope-0.1.0 click-6.7 commonmark-0.5.4 coverage-4.4.1 decorator-4.1.2 dicom-numpy-0.1.1 django-debug-toolbar-1.7 django-dotenv-1.4.1 django-environ-0.4.3 django-extensions-1.7.8 djangorestframework-3.6.3 dnspython-1.15.0 docutils-0.14 email-validator-1.0.2 factory-boy-2.8.1 flake8-3.3.0 idna-2.6 ipython-6.1.0 ipython-genutils-0.2.0 itsdangerous-0.24 jedi-0.10.2 mccabe-0.6.1 numpy-1.13.1 pexpect-4.2.1 pickleshare-0.7.4 prompt-toolkit-1.0.15 psycopg2-2.7.1 ptyprocess-0.5.2 py-1.4.34 pycodestyle-2.3.1 pydicom-0.9.9 pyflakes-1.5.0 pygments-2.2.0 pytest-3.1.3 python-dateutil-2.6.1 recommonmark-0.4.0 simplegeneric-0.8.1 six-1.10.0 sphinx-rtd-theme-0.2.4 sqlparse-0.2.3 traitlets-4.3.2 wcwidth-0.1.7 werkzeug-0.12.2
```

## Possible Implementation
Delete line in `prediction/requirements/local.txt`

## Checklist before submitting
- [x] I have confirmed this using the officially supported Docker Compose setup using the `local.py` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [x] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [x] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [x] I provided **screenshots** where appropriate
- [x] I filled out all the relevant sections of this template

**Comment by isms** [comment]
Thanks for reporting! Closed by fc898d495b85182f02432753f44d8ff0a4302c08, but the documentation is still broken per #90, though this represents a bit of progress in untangling requirements.
