### ISSUE TITLE
Add function that loads MetaImage files

### ISSUE THREAD

**Issue by vessemer** [concept-to-clinic/concept-to-clinic#98]
In the field of low-dose CT, not the only DICOM data format is wildly used, but MetaImage (`.mhd` / `.raw`) is also taken place. The MetaImage is the text-based tagged file format for medical images. As well as the DICOM format, the MetaImage has descriptors along with the raw data.

## Expected Behavior
The `.mhd` / `.raw` files may be read via `SimpleITK`. So `load_itk` should be provided which takes the `itk_path` as an input and return the `np.ndarray` (right now the `load_dicom` returns the np.ndarray which may be different in the future since MetaImage and DICOM have different metadata and it will be the good decision to build a class which will standardise the metadata by parameters). Furthermore, the orchestrate function `load_CT` aimed at handling different medical image formats, so the `load_CT` will take `CT_path` as an input and will decide whether to return the output of `load_dicom` or `load_itk`. 

## Current Behavior
For now, exists only the possibility to read DICOM file format through `load_dicom`. 

## Technical details
This feature should be implemented in the `prediction/src/preprocess` folder

## Acceptance criteria
- [ ] method to load MetaImage (`.mhd` / `.raw`) images into memory
- [ ] method to select apropriate loader function
- [ ] tests for the methods

**Comment by tdraebing** [comment]
I would start working on that. Are there any image files in those formats in the larger data set that will be used for model training/testing later on that could be used for tests? Else I would try to find some.

**Comment by vessemer** [comment]
As far as I saw no changes for more than the week, I've created a pull request.
